import type { AnyToolPlugin, ToolCategory } from '@utoolios/core'
import { tools } from './registry.generated'

/**
 * The tool registry API (docs/13 §5). `tools` is auto-generated by
 * scripts/generate-tools-registry.mjs from the tool folders — adding a folder
 * and running the generator registers a tool with zero edits to this file.
 *
 * Only PUBLISHED tools are exposed to the platform (docs/14 §7).
 */

const published: readonly AnyToolPlugin[] = tools.filter(
  (tool) => tool.config.status === 'published',
)

export function getAllTools(): readonly AnyToolPlugin[] {
  return published
}

export function getToolById(id: string): AnyToolPlugin | undefined {
  return published.find((tool) => tool.config.id === id)
}

export function getToolsByCategory(category: ToolCategory): readonly AnyToolPlugin[] {
  return published.filter((tool) => tool.config.category === category)
}

export function getAllCategories(): readonly ToolCategory[] {
  return [...new Set(published.map((tool) => tool.config.category))]
}

/** Real tools sorted by actual publish date, most recent first (`design/11-homepage.md`) — never a fabricated ranking. */
export function getRecentlyAddedTools(limit = 5): readonly AnyToolPlugin[] {
  return [...published]
    .sort((a, b) => b.config.publishedAt.localeCompare(a.config.publishedAt))
    .slice(0, limit)
}
