// AUTO-GENERATED by scripts/generate-tools-registry.mjs — DO NOT EDIT.
// Regenerate after adding/removing a tool folder: pnpm --filter @utoolios/tools gen
import type { AnyToolPlugin } from '@utoolios/core'
import base64EncoderDecoder from '../developer/base64-encoder-decoder/index'
import jsonFormatter from '../developer/json-formatter/index'
import jwtDecoder from '../developer/jwt-decoder/index'
import compoundInterestCalculator from '../finance/compound-interest-calculator/index'
import loanRepaymentCalculator from '../finance/loan-repayment-calculator/index'
import mortgageCalculator from '../finance/mortgage-calculator/index'
import bmiCalculator from '../health/bmi-calculator/index'
import calorieTdeeCalculator from '../health/calorie-tdee-calculator/index'
import tileCalculator from '../home/tile-calculator/index'
import wordCounter from '../text/word-counter/index'

export const tools: readonly AnyToolPlugin[] = [
  base64EncoderDecoder as unknown as AnyToolPlugin,
  jsonFormatter as unknown as AnyToolPlugin,
  jwtDecoder as unknown as AnyToolPlugin,
  compoundInterestCalculator as unknown as AnyToolPlugin,
  loanRepaymentCalculator as unknown as AnyToolPlugin,
  mortgageCalculator as unknown as AnyToolPlugin,
  bmiCalculator as unknown as AnyToolPlugin,
  calorieTdeeCalculator as unknown as AnyToolPlugin,
  tileCalculator as unknown as AnyToolPlugin,
  wordCounter as unknown as AnyToolPlugin,
]
