// AUTO-GENERATED by scripts/generate-tools-registry.mjs — DO NOT EDIT.
// Regenerate after adding/removing a tool folder: pnpm --filter @utoolios/tools gen
import type { AnyToolPlugin } from '@utoolios/core'
import mortgageCalculator from '../finance/mortgage-calculator/index'
import bmiCalculator from '../health/bmi-calculator/index'
import wordCounter from '../text/word-counter/index'

export const tools: readonly AnyToolPlugin[] = [
  mortgageCalculator as unknown as AnyToolPlugin,
  bmiCalculator as unknown as AnyToolPlugin,
  wordCounter as unknown as AnyToolPlugin,
]
